# Generated by Django 3.2.13 on 2022-11-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayDetail',
            fields=[
                ('playid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('playname', models.CharField(max_length=50)),
                ('genrename', models.CharField(max_length=20)),
                ('playstate', models.CharField(max_length=20)),
                ('playstdate', models.CharField(max_length=20)),
                ('playenddate', models.CharField(max_length=20)),
                ('poster', models.CharField(max_length=20)),
                ('locationname', models.CharField(max_length=30)),
                ('playcast', models.CharField(max_length=50)),
                ('runtime', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('locationid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('playid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.playdetail')),
            ],
        ),
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('relateurl', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=20)),
                ('lgt', models.CharField(max_length=10)),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.playdetail')),
            ],
        ),
    ]
