# Generated by Django 3.2.13 on 2022-11-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetail',
            name='locationid',
            field=models.CharField(max_length=20),
        ),
    ]
