# Generated by Django 3.2.13 on 2022-11-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playdetail',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
