# Generated by Django 3.2.13 on 2022-11-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20221118_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playdetail',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='playdetail',
            name='genrename',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playdetail',
            name='locationid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playdetail',
            name='playid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playdetail',
            name='playstate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playdetail',
            name='runtime',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
